version: '3.8'
services:
    # Web Server
    web:
        build:
            context: .
            dockerfile: web.dockerfile
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - 80:80
    # Database
    database:
        image: mysql:8.0
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}  // from .env file
            - MYSQL_USER=${DB_USERNAME}  // from .env file
            - MYSQL_PASSWORD=${DB_PASSWORD}  // from .env file
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}  // from .env file
        ports:
            - 3306:3306
volumes:
    dbdata: